services:
  web:
    build: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    restart: "on-failure"
    depends_on:
      - cache

  cache:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
